/**
 * V FOR X — File Transfer over the P2P Data Channel
 *
 * Chunked, encrypted file delivery across an already-open RTCDataChannel.
 * Works on the fully static platform: no servers, no relays, no STUN
 * beyond what the pairing flow already uses.
 *
 * PROTOCOL (prefix "VFXFILE1:")
 *   Control frames are plain STRINGS:
 *     VFXFILE1:init|<id>|<name>|<mime>|<size>|<chunkSize>|<chunkCount>|<sha256>
 *     VFXFILE1:done|<id>|<chunkCount>|<sha256>
 *     VFXFILE1:abort|<id>
 *   Payload frames are BINARY (ArrayBuffer): one encrypted chunk each,
 *   in order.
 *
 * CRYPTOGRAPHY
 *   The data channel is already protected by DTLS. On top of that, every
 *   file is encrypted with a fresh random AES-GCM key (generated by the
 *   sender, carried in the transfer metadata). Each chunk uses its own
 *   random 12-byte IV, prepended to the ciphertext so the receiver can
 *   decrypt without prior coordination. The SHA-256 in the frames is over
 *   the PLAINTEXT, so integrity survives reassembly AND decryption.
 *
 *   The same AES layer lets a received file be stored as an ENCRYPTED
 *   dead drop at rest — the dead-drop record keeps the key alongside
 *   (this device only; the key is never transmitted a second time).
 */

const PREFIX = "VFXFILE1:";
export const FILE_TRANSFER_PREFIX = PREFIX;
export const FILE_CHUNK_SIZE = 8192;

export interface FileMeta {
  id: string;
  name: string;
  mime: string;
  size: number;
  chunkSize: number;
  chunkCount: number;
  sha256: string;
}

export interface PreparedTransfer {
  meta: FileMeta;
  chunks: Uint8Array<ArrayBuffer>[];
  /** Base64 of the 32-byte AES-GCM key for this transfer. */
  keyB64: string;
}

export type TransferState =
  | "waiting"
  | "init"
  | "receiving"
  | "complete"
  | "aborted"
  | "error";

export interface TransferProgress {
  received: number;
  total: number;
  bytes: number;
  percent: number;
}

/* ═══════════════════════════════════════════════════════════
   LOW-LEVEL HELPERS
   ═══════════════════════════════════════════════════════════ */

function bytesToB64(bytes: Uint8Array): string {
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}

function b64ToBytes(b64: string): Uint8Array<ArrayBuffer> {
  const binary = atob(b64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

export function aesKeyToB64(key: Uint8Array): string {
  return bytesToB64(key);
}

export function b64ToAesKey(b64: string): Uint8Array<ArrayBuffer> {
  return b64ToBytes(b64);
}

export async function sha256Hex(bytes: Uint8Array<ArrayBuffer>): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export function newTransferId(): string {
  return crypto.randomUUID().replace(/-/g, "").slice(0, 12);
}

/* ═══════════════════════════════════════════════════════════
   SENDER SIDE
   ═══════════════════════════════════════════════════════════ */

/**
 * Hash the file, mint a per-transfer AES key, and slice into chunks.
 * If `bytes` is omitted the caller supplies chunks lazily via
 * `sliceFile` (browser File objects).
 */
export async function prepareFileTransfer(
  file: { name: string; mime: string; size: number },
  bytes: Uint8Array<ArrayBuffer>,
): Promise<PreparedTransfer> {
  if (!crypto?.subtle) throw new Error("Web Crypto unavailable");
  const sha = await sha256Hex(bytes);
  const key = crypto.getRandomValues(new Uint8Array(32));
  const chunkSize = FILE_CHUNK_SIZE;
  const chunkCount = Math.max(1, Math.ceil(bytes.length / chunkSize));
  const chunks: Uint8Array<ArrayBuffer>[] = [];
  for (let i = 0; i < chunkCount; i++) {
    chunks.push(bytes.slice(i * chunkSize, Math.min(bytes.length, (i + 1) * chunkSize)));
  }
  return {
    meta: {
      id: newTransferId(),
      name: file.name,
      mime: file.mime || "application/octet-stream",
      size: bytes.length,
      chunkSize,
      chunkCount,
      sha256: sha,
    },
    chunks,
    keyB64: aesKeyToB64(key),
  };
}

/** Async slice of a browser File (or Blob) as a Uint8Array. */
export async function sliceFile(file: Blob, start: number, end: number): Promise<Uint8Array<ArrayBuffer>> {
  return new Uint8Array(await file.slice(start, end).arrayBuffer());
}

/** Encrypt a chunk: random 12-byte IV prepended to the AES-GCM ciphertext. */
export async function encryptChunk(
  chunk: Uint8Array<ArrayBuffer>,
  keyB64: string,
): Promise<Uint8Array<ArrayBuffer>> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const key = await crypto.subtle.importKey(
    "raw",
    b64ToBytes(keyB64),
    { name: "AES-GCM" },
    false,
    ["encrypt"],
  );
  const ct = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, chunk);
  const out = new Uint8Array(iv.length + ct.byteLength);
  out.set(iv, 0);
  out.set(new Uint8Array(ct), iv.length);
  return out;
}

/** Decrypt a chunk produced by encryptChunk (reads its own IV). */
export async function decryptChunk(
  enc: Uint8Array<ArrayBuffer>,
  keyB64: string,
): Promise<Uint8Array<ArrayBuffer>> {
  if (enc.length < 13) throw new Error("Chunk too short");
  const iv = enc.slice(0, 12);
  const ct = enc.slice(12);
  const key = await crypto.subtle.importKey(
    "raw",
    b64ToBytes(keyB64),
    { name: "AES-GCM" },
    false,
    ["decrypt"],
  );
  const pt = await crypto.subtle.decrypt({ name: "AES-GCM", iv }, key, ct);
  return new Uint8Array(pt);
}

/* ═══════════════════════════════════════════════════════════
   CONTROL FRAMES
   ═══════════════════════════════════════════════════════════ */

export function buildInitFrame(meta: FileMeta): string {
  return [PREFIX + "init", meta.id, meta.name, meta.mime, meta.size, meta.chunkSize, meta.chunkCount, meta.sha256].join("|");
}

export function buildDoneFrame(meta: FileMeta): string {
  return [PREFIX + "done", meta.id, meta.chunkCount, meta.sha256].join("|");
}

export function buildAbortFrame(id: string): string {
  return `${PREFIX}abort|${id}`;
}

export function isFileControl(data: unknown): boolean {
  return typeof data === "string" && (data as string).startsWith(PREFIX);
}

/**
 * Parse a control frame. Returns {kind, id, meta?} or null if malformed.
 * Accepts "init", "done", "abort".
 */
export function parseFileControl(line: string): {
  kind: "init" | "done" | "abort";
  id: string;
  meta?: FileMeta;
} | null {
  if (!isFileControl(line)) return null;
  const parts = line.split("|");
  if (parts.length < 2) return null;
  const kind = parts[0].slice(PREFIX.length); // e.g. "VFXFILE1:init" → "init"
  const id = parts[1];
  if (!id) return null;
  if (kind === "abort") return { kind: "abort", id };
  if (kind === "init") {
    if (parts.length !== 8) return null;
    const size = Number(parts[4]);
    const chunkSize = Number(parts[5]);
    const chunkCount = Number(parts[6]);
    if (!Number.isFinite(size) || !Number.isFinite(chunkSize) || !Number.isFinite(chunkCount)) {
      return null;
    }
    if (chunkCount < 1) return null;
    return {
      kind: "init",
      id,
      meta: {
        id,
        name: parts[2] ?? "file.bin",
        mime: parts[3] ?? "application/octet-stream",
        size,
        chunkSize,
        chunkCount,
        sha256: parts[7] ?? "",
      },
    };
  }
  if (kind === "done") {
    if (parts.length !== 4) return null;
    return { kind: "done", id };
  }
  return null;
}

/* ═══════════════════════════════════════════════════════════
   RECEIVER SIDE
   ═══════════════════════════════════════════════════════════ */

export class FileReceiver {
  private state: TransferState = "waiting";
  private meta: FileMeta | null = null;
  private keyB64 = "";
  private parts: Uint8Array<ArrayBuffer>[] = [];
  private received = 0;
  private assembled: Uint8Array<ArrayBuffer> | null = null;
  private verified = false;
  private resolveDone: (() => void) | null = null;
  private completion: Promise<void>;
  /** Serializes decryption so the done-frame verify never races ahead. */
  private chain: Promise<void> = Promise.resolve();

  constructor() {
    this.completion = new Promise((resolve) => {
      this.resolveDone = resolve;
    });
  }

  getState(): TransferState {
    return this.state;
  }

  getMeta(): FileMeta | null {
    return this.meta;
  }

  getKeyB64(): string {
    return this.keyB64;
  }

  progress(): TransferProgress {
    const total = this.meta?.chunkCount ?? 0;
    return {
      received: this.received,
      total,
      bytes: this.parts.reduce((acc, p) => acc + p.length, 0),
      percent: total === 0 ? 0 : Math.round((this.received / total) * 100),
    };
  }

  /** Resolves when the transfer reaches a terminal state. */
  whenComplete(): Promise<void> {
    return this.completion;
  }

  feedControl(line: string): boolean {
    const parsed = parseFileControl(line);
    if (!parsed) return false;
    if (parsed.kind === "abort") {
      this.state = "aborted";
      this.finish();
      return true;
    }
    if (parsed.kind === "init") {
      // Only accept a new transfer when idle/finished; a stale init
      // mid-transfer is ignored (protects against lost done frames).
      if (this.state === "receiving" || this.state === "init") return true;
      this.meta = parsed.meta ?? null;
      this.parts = [];
      this.received = 0;
      this.assembled = null;
      this.verified = false;
      this.state = "init";
      return true;
    }
    if (parsed.kind === "done") {
      if (this.state === "receiving" || this.state === "init") {
        this.chain = this.chain.then(() => this.finishWithVerify());
      }
      return true;
    }
    return false;
  }

  /** Feed one encrypted binary chunk. */
  feedBinary(buf: ArrayBuffer): boolean {
    if (this.state !== "init" && this.state !== "receiving") return false;
    if (!this.meta) return false;
    this.state = "receiving";
    const chunk = new Uint8Array(buf);
    const meta = this.meta;
    this.chain = this.chain.then(async () => {
      try {
        const plain = await decryptChunk(chunk, this.keyB64);
        this.parts.push(plain);
        this.received += 1;
        if (this.received >= meta.chunkCount && this.state !== "complete" && this.state !== "error") {
          await this.finishWithVerify();
        }
      } catch {
        this.state = "error";
        this.finish();
      }
    });
    return true;
  }

  /**
   * Set the AES key (must be called before feeding binary chunks —
   * the sender transmits it inside the init metadata, the UI passes it
   * from the same source).
   */
  setKey(keyB64: string) {
    this.keyB64 = keyB64;
  }

  /** Assemble + verify the plaintext SHA-256; resolve completion. */
  private async finishWithVerify(): Promise<void> {
    const meta = this.meta;
    if (!meta) {
      this.state = "error";
      this.finish();
      return;
    }
    const totalLen = this.parts.reduce((acc, p) => acc + p.length, 0);
    const out = new Uint8Array(totalLen);
    let offset = 0;
    for (const p of this.parts) {
      out.set(p, offset);
      offset += p.length;
    }
    this.assembled = out;
    try {
      const sha = await sha256Hex(out);
      this.verified = sha === meta.sha256;
      this.state = this.verified ? "complete" : "error";
    } catch {
      this.state = "error";
    }
    this.finish();
  }

  private finish() {
    this.resolveDone?.();
  }

  /** Result when state === "complete". */
  done(): { meta: FileMeta; assembled: Uint8Array<ArrayBuffer>; sha256Verified: boolean } | null {
    if (this.state !== "complete" || !this.meta || !this.assembled) return null;
    return { meta: this.meta, assembled: this.assembled, sha256Verified: this.verified };
  }

  discard() {
    this.state = "aborted";
    this.parts = [];
    this.assembled = null;
    this.finish();
  }
}

/* ═══════════════════════════════════════════════════════════
   DEAD-DROP FILE ENVELOPE
   ═══════════════════════════════════════════════════════════ */

export interface DeadDropFileRecord {
  id: string;
  lat: string;
  lng: string;
  kind: "file";
  meta: { name: string; mime: string; size: number; sha256: string };
  /** Each encrypted chunk, base64 (IV-prefixed, one entry per chunk). */
  payloadChunksB64: string[];
  /** AES-GCM key (this device only — never transmitted again). */
  keyB64: string;
  ts: number;
  author: string;
}

/**
 * Build a dead-drop record from an encrypted transfer result.
 * The per-chunk boundaries are preserved so the whole file can be
 * decrypted later without re-deriving chunk layout.
 */
export async function buildDeadDropFileRecord(
  input: {
    id: string;
    lat: string;
    lng: string;
    meta: FileMeta;
    encryptedChunks: Uint8Array<ArrayBuffer>[];
    keyB64: string;
    ts: number;
    author: string;
  },
): Promise<DeadDropFileRecord> {
  return {
    id: input.id,
    lat: input.lat,
    lng: input.lng,
    kind: "file",
    meta: { name: input.meta.name, mime: input.meta.mime, size: input.meta.size, sha256: input.meta.sha256 },
    payloadChunksB64: input.encryptedChunks.map(bytesToB64),
    keyB64: input.keyB64,
    ts: input.ts,
    author: input.author,
  };
}

/** Decrypt a stored dead-drop file, returning the plaintext bytes. */
export async function decryptDeadDropFile(
  record: DeadDropFileRecord,
): Promise<Uint8Array<ArrayBuffer>> {
  const out: Uint8Array<ArrayBuffer>[] = [];
  for (const b64 of record.payloadChunksB64) {
    out.push(await decryptChunk(b64ToBytes(b64), record.keyB64));
  }
  const total = out.reduce((acc, p) => acc + p.length, 0);
  const result = new Uint8Array(total);
  let offset = 0;
  for (const p of out) {
    result.set(p, offset);
    offset += p.length;
  }
  return result;
}
